### PR TITLE
build more platforms

### PR DESCRIPTION
**Pull request by cancan101**
@matthew-brett can I get you to add the key to this repos too?

### CODE REVIEW

**Comment by matthew-brett** [comment]
I think you need to use these env vars at the end wheel-uploader command - or did I miss something?

These containers are both on the same account, so the same key should work for both.

**Comment by cancan101** [comment]
Yea I left that off will add deploy in another pr.
I think the key is encrypted repo specific so would need to be redone for this repos.

**Comment by matthew-brett** [comment]
Oh - whoops - sorry I didn't see this was a new repo.

**Comment by cancan101** [comment]
Yep rolling forward. One more wheel to build 😉

**Comment by matthew-brett** [comment]
https://github.com/cancan101/pyNFFT-wheels/pull/3

**Pull request merged**
